ALTER TABLE events ADD COLUMN image_focus_x INTEGER NOT NULL DEFAULT 50;
ALTER TABLE events ADD COLUMN image_focus_y INTEGER NOT NULL DEFAULT 50;

ALTER TABLE review_candidates ADD COLUMN image_focus_x INTEGER NOT NULL DEFAULT 50;
ALTER TABLE review_candidates ADD COLUMN image_focus_y INTEGER NOT NULL DEFAULT 50;

ALTER TABLE image_assets ADD COLUMN focus_x INTEGER NOT NULL DEFAULT 50;
ALTER TABLE image_assets ADD COLUMN focus_y INTEGER NOT NULL DEFAULT 50;
